server:
  port: 18003   # 和你模块名对应

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eurekaServer18003
  client:
    # 下面两个 false 很关键：自己是注册中心，不用注册自己
    service-url:
      defaultZone: http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/